// Cached AccuLynx US state IDs — generated 2026-04-29
export const ACCULYNX_US_STATES = {
  'AL': { id: 1, name: 'Alabama' },
  'AK': { id: 2, name: 'Alaska' },
  'AZ': { id: 3, name: 'Arizona' },
  'AR': { id: 4, name: 'Arkansas' },
  'CA': { id: 5, name: 'California' },
  'CO': { id: 6, name: 'Colorado' },
  'CT': { id: 7, name: 'Connecticut' },
  'DE': { id: 8, name: 'Delaware' },
  'FL': { id: 9, name: 'Florida' },
  'GA': { id: 10, name: 'Georgia' },
  'HI': { id: 11, name: 'Hawaii' },
  'ID': { id: 12, name: 'Idaho' },
  'IL': { id: 13, name: 'Illinois' },
  'IN': { id: 14, name: 'Indiana' },
  'IA': { id: 15, name: 'Iowa' },
  'KS': { id: 16, name: 'Kansas' },
  'KY': { id: 17, name: 'Kentucky' },
  'LA': { id: 18, name: 'Louisiana' },
  'ME': { id: 19, name: 'Maine' },
  'MD': { id: 20, name: 'Maryland' },
  'MA': { id: 21, name: 'Massachusetts' },
  'MI': { id: 22, name: 'Michigan' },
  'MN': { id: 23, name: 'Minnesota' },
  'MS': { id: 24, name: 'Mississippi' },
  'MO': { id: 25, name: 'Missouri' },
  'MT': { id: 26, name: 'Montana' },
  'NE': { id: 27, name: 'Nebraska' },
  'NV': { id: 28, name: 'Nevada' },
  'NH': { id: 29, name: 'New Hampshire' },
  'NJ': { id: 30, name: 'New Jersey' },
  'NM': { id: 31, name: 'New Mexico' },
  'NY': { id: 32, name: 'New York' },
  'NC': { id: 33, name: 'North Carolina' },
  'ND': { id: 34, name: 'North Dakota' },
  'OH': { id: 35, name: 'Ohio' },
  'OK': { id: 36, name: 'Oklahoma' },
  'OR': { id: 37, name: 'Oregon' },
  'PA': { id: 38, name: 'Pennsylvania' },
  'RI': { id: 39, name: 'Rhode Island' },
  'SC': { id: 40, name: 'South Carolina' },
  'SD': { id: 41, name: 'South Dakota' },
  'TN': { id: 42, name: 'Tennessee' },
  'TX': { id: 43, name: 'Texas' },
  'UT': { id: 44, name: 'Utah' },
  'VT': { id: 45, name: 'Vermont' },
  'VA': { id: 46, name: 'Virginia' },
  'WA': { id: 47, name: 'Washington' },
  'WV': { id: 48, name: 'West Virginia' },
  'WI': { id: 49, name: 'Wisconsin' },
  'WY': { id: 50, name: 'Wyoming' },
  'DC': { id: 64, name: 'Washington-DC' },
  'PR': { id: 65, name: 'Puerto Rico' },
  'VI': { id: 66, name: 'U.S. Virgin Islands' },
  'GU': { id: 67, name: 'Guam' },
};
